# Generated by Django 5.1.4 on 2025-02-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_cage_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/staff/'),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/veterinarian/'),
        ),
    ]
