# Generated by Django 5.1.4 on 2025-02-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pet_age_alter_pet_name_pet_alter_pet_species_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
