# Generated by Django 5.1.4 on 2025-02-18 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_staff_images_veterinarian_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number_staff',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='staff',
            name='real_name_Staff',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='CageType',
        ),
    ]
