# Generated by Django 5.1.4 on 2025-02-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_pet_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/customer/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/pet/'),
        ),
    ]
