# Generated by Django 5.1.4 on 2025-02-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_staff_phone_number_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='phone_number_staff',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
