# Generated by Django 5.1.4 on 2025-02-18 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_staff_phone_number_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cagestatus',
            name='dirty',
        ),
    ]
