# Generated by Django 5.1.4 on 2025-02-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='is_male',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
