# Generated by Django 5.1.4 on 2025-02-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customuser_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
