# Generated by Django 5.1.4 on 2025-02-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_pet_is_male'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='name_pet',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
