# Generated by Django 5.1.4 on 2025-02-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_male',
            field=models.BooleanField(default=True),
        ),
    ]
