# Generated by Django 5.1.4 on 2025-02-07 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_pet_is_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='additional_fee',
        ),
        migrations.AddField(
            model_name='cost',
            name='extra_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cost',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
