# Generated by Django 5.1.4 on 2025-02-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pet_name_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet_status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
