# Generated by Django 5.1.4 on 2025-02-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_cost_additional_fee_cost_extra_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='store_pet',
            field=models.BooleanField(default=False),
        ),
    ]
