# Generated by Django 5.1.4 on 2025-02-11 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_schedule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='booking_date',
        ),
    ]
