# Generated by Django 5.1.4 on 2025-02-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='extra_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cost',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
