# Generated by Django 5.1.4 on 2025-02-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cost_extra_fee_alter_cost_service_fee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FormBooking',
        ),
        migrations.AlterField(
            model_name='bookingstatus',
            name='awaiting',
            field=models.BooleanField(default=True),
        ),
    ]
