# Generated by Django 5.1.4 on 2025-02-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_form_formbooking_alter_bookingstatus_awaiting'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('veterinarian', 'date'), name='unique_schedule_per_vet_per_day'),
        ),
    ]
