# Generated by Django 5.1.4 on 2025-02-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_schedule_unique_schedule_per_vet_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='real_name_Staff',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='veterinarian',
            name='real_name_veterinarian',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
