# Generated by Django 5.1.4 on 2025-02-11 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_appointmentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='appointment_date',
        ),
    ]
